---
layout: page
title:  "Encuestas Presidenciales 2016"
subheadline:  "Elecciones presidenciales"
teaser: "Presentamos los resultados de las encuestas para las elecciones presidenciales 2016"
categories:
    - "seguimiento"
tags:
    - seguimiento
    - Elecciones presidenciales
    - 2016 
show_meta: false
breadcrumb: true
---



```{r, results='asis',echo= FALSE,cache=FALSE,warning=FALSE,message=FALSE}
library("devtools")
library(plotly)
library(servr)
library(ggplot2)
library(data.table)

library(knitr)

ruta <- getwd()

ruta <- gsub("/_source","",ruta)

ruta_in <- paste0(ruta,"/data/")
Sys.setenv("plotly_username"="alejandrokantor")
Sys.setenv("plotly_api_key"="c9vh7zksao")

load(file=paste0(ruta_in,"encuestasPrimeraVueltaLong.RData"))
dt_long <- dt_long[ Candidato!="Suma"]


v_candidatos <- levels(dt_long[,Candidato])
v_candidatos <- setdiff(v_candidatos, "Suma")

#inicializacion de for
k_candidato <- v_candidatos[1]
py <- plot_ly(data = dt_long[ Candidato==k_candidato], x = Fecha_inicio, y = Valor, 
              name =  unique(Candidato), mode = "markers", filename="r-docs/encuesta" ,fileopt="overwrite") 
py <- py %>% add_trace(data = dt_long[ Candidato==k_candidato], mode="lines",x=as.Date(x=16697:16521,origin = "1970-01-01"),
                       y =  predict(object =loess(Valor ~ as.numeric(Fecha_inicio)),  
                                    data.frame(Fecha_inicio= 16697:16521)), name =  unique(Candidato), 
                       filename="r-docs/encuesta",fileopt="overwrite")
py


rm(k_candidato)

for( i in 2:length(v_candidatos)){
  k_candidato <- v_candidatos[i]
  py <- py %>%  add_trace(data = dt_long[ Candidato==k_candidato], x = Fecha_inicio, y = Valor, 
                    name = unique(Candidato), mode = "markers",  filename="r-docs/encuesta",visible="legendonly")
  rm(k_candidato)
  rm(i)
}

py


#servr::jekyll()
```

<!--# o de esta manera-->

<iframe height="600" id="igraph" scrolling="no" seamless="seamless" src="https://plot.ly/~AlejandroKantor/31.embed" width="800" frameBorder="0"></iframe>


```{r, results='asis',echo=FALSE, warning=FALSE,comment = NA,message=FALSE, tidy=FALSE}


```


